"""add roles and role_id to users

Revision ID: 2d8108ba1e4f
Revises: 
Create Date: 2025-12-04 21:05:18.461259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8108ba1e4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    # op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=False)
    op.drop_column('user', 'role_id')
    # ### end Alembic commands ###
